POST http://localhost:8030/domain-events
Content-Type: application/json

{
  "eventName": "course.created",
  "eventRaw": {
    "data": {
      "id": "{{$random.uuid}}",
      "type": "course.created",
      "occurred_on": "2023-11-14 10:00:00",
      "attributes": {
        "id": "9bd0c98a-92cc-4a56-a5a1-7d40839ddc83",
        "name": "Demo course",
        "duration": "2 days"
      }
    },
    "meta": {
    }
  }
}

###
POST http://localhost:8030/domain-events
Content-Type: application/json

{
  "eventName": "course.renamed",
  "eventRaw": {
    "data": {
      "id": "{{$random.uuid}}",
      "type": "course.renamed",
      "occurred_on": "2023-11-14 10:00:00",
      "attributes": {
        "id": "9bd0c98a-92cc-4a56-a5a1-7d40839ddc83",
        "name": "heeey 22222"
      }
    },
    "meta": {
    }
  }
}
