name: Modified

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch master
        run: git fetch --all

      - name: 😮 Modified contexts in this Pull Request
        run: git diff --name-status origin/master | grep "src/" | awk -F '/' '{print $2}' | uniq
