name: Modified

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: View modified context
        run: |
        echo "Modified contexts"
        make modified-contexts
